#import "RNInstalledAppChecker.h"
#import <React/RCTLog.h>
#import <UIKit/UIKit.h>

@implementation RNInstalledAppChecker

RCT_EXPORT_MODULE();

// Belirli bir uygulamanın yüklü olup olmadığını kontrol eder
RCT_EXPORT_METHOD(isAppInstalled:(NSString *)urlScheme
                  callback:(RCTResponseSenderBlock)callback)
{
    NSURL *url = [NSURL URLWithString:urlScheme];
    BOOL isInstalled = [[UIApplication sharedApplication] canOpenURL:url];
    callback(@[@(isInstalled)]);
}

// Yaygın uygulamaların URL scheme'lerini döndürür
RCT_EXPORT_METHOD(getInstalledApps:(RCTResponseSenderBlock)callback)
{
    NSMutableArray *installedApps = [[NSMutableArray alloc] init];
    
    // Yaygın uygulamaların URL scheme'leri
    NSDictionary *commonApps = @{
        @"whatsapp": @"whatsapp://",
        @"telegram": @"tg://",
        @"instagram": @"instagram://",
        @"facebook": @"fb://",
        @"twitter": @"twitter://",
        @"youtube": @"youtube://",
        @"spotify": @"spotify://",
        @"netflix": @"nflx://",
        @"uber": @"uber://",
        @"maps": @"comgooglemaps://",
        @"gmail": @"googlegmail://",
        @"chrome": @"googlechrome://",
        @"skype": @"skype://",
        @"linkedin": @"linkedin://",
        @"snapchat": @"snapchat://",
        @"tiktok": @"tiktok://",
        @"discord": @"discord://",
        @"zoom": @"zoomus://",
        @"slack": @"slack://",
        @"dropbox": @"dbapi-1://",
        @"onedrive": @"ms-onedrive://",
        @"paypal": @"paypal://",
        @"amazon": @"amazon://",
        @"ebay": @"ebay://",
        @"airbnb": @"airbnb://",
        @"booking": @"booking://",
        @"tripadvisor": @"tripadvisor://",
        @"pinterest": @"pinterest://",
        @"reddit": @"reddit://",
        @"twitch": @"twitch://",
        @"viber": @"viber://",
        @"line": @"line://",
        @"wechat": @"wechat://",
        @"alipay": @"alipay://",
        @"paytm": @"paytm://",
        @"phonepe": @"phonepe://",
        @"gpay": @"gpay://",
        @"paypal": @"paypal://",
        @"venmo": @"venmo://",
        @"cashapp": @"cashme://",
        @"zelle": @"zelle://",
        @"bankofamerica": @"bofa://",
        @"chase": @"chase://",
        @"wellsfargo": @"wellsfargo://",
        @"citibank": @"citibank://",
        @"capitalone": @"capitalone://",
        @"usbank": @"usbank://",
        @"pnc": @"pnc://",
        @"tdbank": @"tdbank://",
        @"regions": @"regions://",
        @"suntrust": @"suntrust://",
        @"bbt": @"bbt://",
        @"huntington": @"huntington://",
        @"keybank": @"keybank://",
        @"fifththird": @"fifththird://",
        @"comerica": @"comerica://",
        @"m&t": @"mtbank://",
        @"citizens": @"citizens://",
        @"firstcitizens": @"firstcitizens://",
        @"synchrony": @"synchrony://",
        @"discover": @"discover://",
        @"americanexpress": @"amex://",
        @"mastercard": @"mastercard://",
        @"visa": @"visa://",
        @"applepay": @"applepay://",
        @"samsungpay": @"samsungpay://",
        @"googlepay": @"googlepay://",
        @"paypal": @"paypal://",
        @"stripe": @"stripe://",
        @"square": @"square://",
        @"quickbooks": @"quickbooks://",
        @"freshbooks": @"freshbooks://",
        @"xero": @"xero://",
        @"mint": @"mint://",
        @"ynab": @"ynab://",
        @"pocketguard": @"pocketguard://",
        @"claritymoney": @"claritymoney://",
        @"goodbudget": @"goodbudget://",
        @"everydollar": @"everydollar://",
        @"honeydue": @"honeydue://",
        @"splitwise": @"splitwise://",
        @"venmo": @"venmo://",
        @"cashapp": @"cashme://",
        @"zelle": @"zelle://",
        @"paypal": @"paypal://",
        @"applepay": @"applepay://",
        @"googlepay": @"googlepay://",
        @"samsungpay": @"samsungpay://",
        @"amazonpay": @"amazonpay://",
        @"shopify": @"shopify://",
        @"etsy": @"etsy://",
        @"ebay": @"ebay://",
        @"amazon": @"amazon://",
        @"walmart": @"walmart://",
        @"target": @"target://",
        @"costco": @"costco://",
        @"homedepot": @"homedepot://",
        @"lowes": @"lowes://",
        @"bestbuy": @"bestbuy://",
        @"macys": @"macys://",
        @"nordstrom": @"nordstrom://",
        @"zappos": @"zappos://",
        @"asos": @"asos://",
        @"h&m": @"hm://",
        @"zara": @"zara://",
        @"uniqlo": @"uniqlo://",
        @"gap": @"gap://",
        @"oldnavy": @"oldnavy://",
        @"bananarepublic": @"bananarepublic://",
        @"athleta": @"athleta://",
        @"jcrew": @"jcrew://",
        @"madewell": @"madewell://",
        @"everlane": @"everlane://",
        @"reformation": @"reformation://",
        @"allbirds": @"allbirds://",
        @"warbyparker": @"warbyparker://",
        @"glossier": @"glossier://",
        @"sephora": @"sephora://",
        @"ulta": @"ulta://",
        @"mac": @"mac://",
        @"nars": @"nars://",
        @"urbanoutfitters": @"urbanoutfitters://",
        @"anthropologie": @"anthropologie://",
        @"freepeople": @"freepeople://",
        @"bhl": @"bhl://",
        @"terrain": @"terrain://",
        @"westelm": @"westelm://",
        @"potterybarn": @"potterybarn://",
        @"williamssonoma": @"williamssonoma://",
        @"crateandbarrel": @"crateandbarrel://",
        @"restorationhardware": @"restorationhardware://",
        @"wayfair": @"wayfair://",
        @"overstock": @"overstock://",
        @"homedepot": @"homedepot://",
        @"lowes": @"lowes://",
        @"menards": @"menards://",
        @"acehardware": @"acehardware://",
        @"tractorsupply": @"tractorsupply://",
        @"harborfreight": @"harborfreight://",
        @"northern": @"northern://",
        @"fastenal": @"fastenal://",
        @"grainger": @"grainger://",
        @"mcmaster": @"mcmaster://",
        @"mscdirect": @"mscdirect://",
        @"zoro": @"zoro://",
        @"globalindustrial": @"globalindustrial://",
        @"uline": @"uline://",
        @"staples": @"staples://",
        @"officedepot": @"officedepot://",
        @"officemax": @"officemax://",
        @"amazonbusiness": @"amazonbusiness://",
        @"walmartbusiness": @"walmartbusiness://",
        @"costcobusiness": @"costcobusiness://",
        @"samsclub": @"samsclub://",
        @"bjs": @"bjs://",
        @"kroger": @"kroger://",
        @"safeway": @"safeway://",
        @"albertsons": @"albertsons://",
        @"publix": @"publix://",
        @"wegmans": @"wegmans://",
        @"wholefoods": @"wholefoods://",
        @"traderjoes": @"traderjoes://",
        @"sprouts": @"sprouts://",
        @"freshmarket": @"freshmarket://",
        @"harristeeter": @"harristeeter://",
        @"giant": @"giant://",
        @"stopandshop": @"stopandshop://",
        @"foodlion": @"foodlion://",
        @"hannaford": @"hannaford://",
        @"pricechopper": @"pricechopper://",
        @"tops": @"tops://",
        @"wegmans": @"wegmans://",
        @"tops": @"tops://",
        @"pricechopper": @"pricechopper://",
        @"hannaford": @"hannaford://",
        @"foodlion": @"foodlion://",
        @"stopandshop": @"stopandshop://",
        @"giant": @"giant://",
        @"harristeeter": @"harristeeter://",
        @"freshmarket": @"freshmarket://",
        @"sprouts": @"sprouts://",
        @"traderjoes": @"traderjoes://",
        @"wholefoods": @"wholefoods://",
        @"wegmans": @"wegmans://",
        @"publix": @"publix://",
        @"albertsons": @"albertsons://",
        @"safeway": @"safeway://",
        @"kroger": @"kroger://",
        @"bjs": @"bjs://",
        @"samsclub": @"samsclub://",
        @"costcobusiness": @"costcobusiness://",
        @"walmartbusiness": @"walmartbusiness://",
        @"amazonbusiness": @"amazonbusiness://",
        @"officemax": @"officemax://",
        @"officedepot": @"officedepot://",
        @"staples": @"staples://",
        @"uline": @"uline://",
        @"globalindustrial": @"globalindustrial://",
        @"zoro": @"zoro://",
        @"mscdirect": @"mscdirect://",
        @"mcmaster": @"mcmaster://",
        @"grainger": @"grainger://",
        @"fastenal": @"fastenal://",
        @"northern": @"northern://",
        @"harborfreight": @"harborfreight://",
        @"tractorsupply": @"tractorsupply://",
        @"acehardware": @"acehardware://",
        @"menards": @"menards://",
        @"lowes": @"lowes://",
        @"homedepot": @"homedepot://",
        @"overstock": @"overstock://",
        @"wayfair": @"wayfair://",
        @"restorationhardware": @"restorationhardware://",
        @"crateandbarrel": @"crateandbarrel://",
        @"williamssonoma": @"williamssonoma://",
        @"potterybarn": @"potterybarn://",
        @"westelm": @"westelm://",
        @"terrain": @"terrain://",
        @"bhl": @"bhl://",
        @"freepeople": @"freepeople://",
        @"anthropologie": @"anthropologie://",
        @"urbanoutfitters": @"urbanoutfitters://",
        @"nars": @"nars://",
        @"mac": @"mac://",
        @"ulta": @"ulta://",
        @"sephora": @"sephora://",
        @"glossier": @"glossier://",
        @"warbyparker": @"warbyparker://",
        @"allbirds": @"allbirds://",
        @"reformation": @"reformation://",
        @"everlane": @"everlane://",
        @"madewell": @"madewell://",
        @"jcrew": @"jcrew://",
        @"athleta": @"athleta://",
        @"bananarepublic": @"bananarepublic://",
        @"oldnavy": @"oldnavy://",
        @"gap": @"gap://",
        @"uniqlo": @"uniqlo://",
        @"zara": @"zara://",
        @"h&m": @"hm://",
        @"asos": @"asos://",
        @"zappos": @"zappos://",
        @"nordstrom": @"nordstrom://",
        @"macys": @"macys://",
        @"bestbuy": @"bestbuy://",
        @"lowes": @"lowes://",
        @"homedepot": @"homedepot://",
        @"costco": @"costco://",
        @"target": @"target://",
        @"walmart": @"walmart://",
        @"amazon": @"amazon://",
        @"ebay": @"ebay://",
        @"etsy": @"etsy://",
        @"shopify": @"shopify://",
        @"samsungpay": @"samsungpay://",
        @"googlepay": @"googlepay://",
        @"applepay": @"applepay://",
        @"zelle": @"zelle://",
        @"cashapp": @"cashme://",
        @"venmo": @"venmo://",
        @"paypal": @"paypal://",
        @"splitwise": @"splitwise://",
        @"honeydue": @"honeydue://",
        @"everydollar": @"everydollar://",
        @"goodbudget": @"goodbudget://",
        @"claritymoney": @"claritymoney://",
        @"pocketguard": @"pocketguard://",
        @"ynab": @"ynab://",
        @"mint": @"mint://",
        @"xero": @"xero://",
        @"freshbooks": @"freshbooks://",
        @"quickbooks": @"quickbooks://",
        @"square": @"square://",
        @"stripe": @"stripe://",
        @"paypal": @"paypal://",
        @"googlepay": @"googlepay://",
        @"samsungpay": @"samsungpay://",
        @"applepay": @"applepay://",
        @"visa": @"visa://",
        @"mastercard": @"mastercard://",
        @"americanexpress": @"amex://",
        @"discover": @"discover://",
        @"synchrony": @"synchrony://",
        @"firstcitizens": @"firstcitizens://",
        @"citizens": @"citizens://",
        @"m&t": @"mtbank://",
        @"comerica": @"comerica://",
        @"fifththird": @"fifththird://",
        @"keybank": @"keybank://",
        @"huntington": @"huntington://",
        @"bbt": @"bbt://",
        @"suntrust": @"suntrust://",
        @"regions": @"regions://",
        @"tdbank": @"tdbank://",
        @"pnc": @"pnc://",
        @"usbank": @"usbank://",
        @"capitalone": @"capitalone://",
        @"citibank": @"citibank://",
        @"wellsfargo": @"wellsfargo://",
        @"chase": @"chase://",
        @"bankofamerica": @"bofa://",
        @"zelle": @"zelle://",
        @"cashapp": @"cashme://",
        @"venmo": @"venmo://",
        @"paypal": @"paypal://",
        @"gpay": @"gpay://",
        @"phonepe": @"phonepe://",
        @"paytm": @"paytm://",
        @"alipay": @"alipay://",
        @"wechat": @"wechat://",
        @"line": @"line://",
        @"viber": @"viber://",
        @"twitch": @"twitch://",
        @"reddit": @"reddit://",
        @"pinterest": @"pinterest://",
        @"tripadvisor": @"tripadvisor://",
        @"booking": @"booking://",
        @"airbnb": @"airbnb://",
        @"ebay": @"ebay://",
        @"amazon": @"amazon://",
        @"paypal": @"paypal://",
        @"onedrive": @"ms-onedrive://",
        @"dropbox": @"dbapi-1://",
        @"slack": @"slack://",
        @"zoom": @"zoomus://",
        @"discord": @"discord://",
        @"tiktok": @"tiktok://",
        @"snapchat": @"snapchat://",
        @"linkedin": @"linkedin://",
        @"skype": @"skype://",
        @"chrome": @"googlechrome://",
        @"gmail": @"googlegmail://",
        @"maps": @"comgooglemaps://",
        @"uber": @"uber://",
        @"netflix": @"nflx://",
        @"spotify": @"spotify://",
        @"youtube": @"youtube://",
        @"twitter": @"twitter://",
        @"facebook": @"fb://",
        @"instagram": @"instagram://",
        @"telegram": @"tg://",
        @"whatsapp": @"whatsapp://"
    };
    
    for (NSString *appName in commonApps.allKeys) {
        NSString *urlScheme = commonApps[appName];
        NSURL *url = [NSURL URLWithString:urlScheme];
        BOOL isInstalled = [[UIApplication sharedApplication] canOpenURL:url];
        
        if (isInstalled) {
            NSDictionary *appInfo = @{
                @"appName": appName,
                @"packageName": urlScheme,
                @"urlScheme": urlScheme,
                @"isInstalled": @YES
            };
            [installedApps addObject:appInfo];
        }
    }
    
    callback(@[installedApps]);
}

// Tüm yüklü uygulamaları döndürür (aynı sonuç, iOS'ta fark yok)
RCT_EXPORT_METHOD(getAllInstalledApps:(RCTResponseSenderBlock)callback)
{
    [self getInstalledApps:callback];
}

@end
